#!/bin/bash

#Check if removed-but-not-purged
test -x /usr/share/logwatch/scripts/logwatch.pl || exit 0

currentdate=$(date +"%m_%d_%Y")

#execute
/usr/sbin/logwatch --output file --filename "/var/log/logwatch-${currentdate}.txt" --format text --detail high --range yesterday

#Note: It's possible to force the recipient in above command
#Just pass --mailto address@a.com instead of --output mail
